importing:  # this will be how imports are done through this, uses relative imports
  database: ../database.yaml

iex_uploader:
  path    : /home/jackh
  message : dividends
  schema  : stockbois
  table   : dividends
  db_acc  : stockbois_writer
